# Set the base image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

# Set the working directory
WORKDIR /app

# Copy the csproj file and restore any dependencies
COPY ./API.csproj ./
RUN dotnet restore

# Copy the remaining files
COPY ./ ./

# Build the application
RUN dotnet publish -c Release -o out

# Generate the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .

# Expose port 80 for incoming traffic
EXPOSE 80

# Start the application
ENTRYPOINT ["dotnet", "API.dll"]